### ISSUE TITLE
Chat not found - Telegram ID correct?

### ISSUE THREAD

**Issue by SebiWolze** [DanJunior78/Repetier-Server-Telegram-Bot#2]
Vorab, bin Deutscher, können gern auch auf Deutsch quatschen oder bei Telegram schreiben. 
Danke für deine Hilfe und deine Arbeit vorab.

Installed your Telegram Bot on my pi4 with repetier Server Pro
Me and my colleague get the same errors on different Operating systems, I guess somethings wrong about the config.json.

In your .json example file, there are no " " marks at the "My Telegram ID" - but if i write my ID (Sebi91/@Sebi91) down without at marks, it says "no config found".

My Config.Json:

` {"CFG_VERSION": "V03", "LANGUAGE": "de", "MY_REPETIER_SERVER_API_KEY": "blablabla", "RepetierServerIP": "10.0.0.10", "RepetierServerIP2": "", "RepetierServerPort": "3344", "MY_TELEGRAM_ID": "@Sebi91", "MY_TELEGRAM_TOKEN": "blablablubb", "LOGFILENAME": "/root/Repetier-Server-Telegram-Bot/log/201123_230922_Repetier-Server_Telegram_Bot.log", "LOGFILENAMEWS": "/root/Repetier-Server-Telegram-Bot/log/201123_230922_Repetier-Server_Telegram_BotWebsocket.log", "PNGFILEFOLDER": "/root/Repetier-Server-Telegram-Bot/pic/png", "GIFFILEFOLDER": "/root/Repetier-Server-Telegram-Bot/pic/gif", "VIDFILEFOLDER": "/root/Repetier-Server-Telegram-Bot/vid", "data": [{"printer": "Prusa_Mini", "name": "Prusa Mini", "telegramHistory": false}, {"printer": "Caribou", "name": "Caribou", "telegramHistory": false}]}
`
Fehlermeldung in Bash:

```

root@Repetier-Server:~/Repetier-Server-Telegram-Bot# python3 Repetier-Server_Telegram_Bot.py
/usr/local/lib/python3.7/dist-packages/telegram/ext/conversationhandler.py:234: UserWarning: If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
  warnings.warn("If 'per_message=False', 'CallbackQueryHandler' will not be "
Exception in thread Repetier-Server-Order-Data:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "Repetier-Server_Telegram_Bot.py", line 822, in run
    self.execute(*self.args, **self.kwargs)
  File "Repetier-Server_Telegram_Bot.py", line 1886, in ThreadHdlOrderData
    feedbackMsg = telegramSendMsg(printerBuffer['name'] + _(" hinzugefuegt"),reply_markup=None, chat_id=CHATID, token=MY_TELEGRAM_TOKEN),
  File "Repetier-Server_Telegram_Bot.py", line 264, in telegramSendMsg
    reply_markup=reply_markup)
  File "<decorator-gen-2>", line 2, in send_message
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 78, in decorator
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 385, in send_message
    timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 215, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/bot.py", line 185, in _post
    timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 328, in post
    **urlopen_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telegram/utils/request.py", line 250, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Chat not found
```

Fehlermeldung in Logfile:
```

(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,293 - Main Thread - INFO - Logger: Main Thread wurde im Debug Modus(False) aktiviert. Level: 20 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,293 - WS Thread - INFO - Logger: WS Thread wurde im Debug Modus(False) aktiviert. Level: 20 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,294 - Main Thread - INFO - Sprachedateipfad: /root/Repetier-Server-Telegram-Bot/locale 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,295 - Main Thread - INFO - Sprache auf "None" umgestellt 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,300 - Main Thread - INFO - ########### Repetier-Server Bot ########### 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,300 - Main Thread - INFO - Software Version: 0.3 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,300 - Main Thread - INFO - Thread name: Repetier-Server_Telegram_Bot 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,300 - Main Thread - INFO - ########### Geraete and Python Information ########### 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,300 - Main Thread - INFO - Python version: 3.7.3 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,301 - Main Thread - INFO - OS: Linux 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,301 - Main Thread - INFO - OS Version: Linux-5.4.51-v7l+-armv7l-with-debian-10.4 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,301 - Main Thread - INFO - Active user: root
 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,301 - Main Thread - INFO - Konfigurationsversion stimmt ueberein: V03 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,301 - Main Thread - INFO - Language Repetier Server: de 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,302 - Main Thread - INFO - Language file path: /root/Repetier-Server-Telegram-Bot/locale 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,302 - Main Thread - INFO - Changed language to "de" 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,309 - Main Thread - INFO - API Key Repetier Server: XY 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - Repetier Server IP: 10.0.0.10 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - Repetier Server IP2:  
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - Repetier Server Port: 3344 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - Telegram Token: XY 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - Administrator Telegram ID: Sebi91 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - LogFileName: /root/Repetier-Server-Telegram-Bot/log/201123_230922_Repetier-Server_Telegram_Bot.log 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,310 - Main Thread - INFO - LogFileNameWS: /root/Repetier-Server-Telegram-Bot/log/201123_230922_Repetier-Server_Telegram_BotWebsocket.log 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,311 - Main Thread - INFO - PNGFileFolder: /root/Repetier-Server-Telegram-Bot/pic/png 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,311 - Main Thread - INFO - GIFFileFolder: /root/Repetier-Server-Telegram-Bot/pic/gif 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,311 - Main Thread - INFO - VIDFileFolder: /root/Repetier-Server-Telegram-Bot/vid 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,311 - Main Thread - INFO - Configuration file read successful: /root/Repetier-Server-Telegram-Bot/Repetier-Server_Telegram_Bot.json 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,313 - WS Thread - INFO - Thread initialisiert: Repetier-Server-Send 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,314 - WS Thread - INFO - Thread initialisiert: Repetier-Server-Receive 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,314 - WS Thread - INFO - Thread initialisiert: Repetier-Server-Order-Data 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,314 - WS Thread - INFO - Thread initialisiert: Repetier-Server-Restart-Threads 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,320 - WS Thread - INFO - Websocket established to: ws://10.0.0.10:3344/socket/?lang=de&&apikey=bd9361cd-5f5c-4837-a30f-2b199d8e467b 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,428 - WS Thread - INFO - Handler Prusa_Mini hinzugefuegt 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,428 - Main Thread - INFO - Teilnehmer in botData hinzugefuegt: Prusa Mini 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,428 - WS Thread - INFO - Handler Caribou hinzugefuegt 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,429 - Main Thread - INFO - Teilnehmer in botData hinzugefuegt: Caribou 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,429 - WS Thread - INFO - Bot Data angelegt 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,683 - WS Thread - ERROR - Konnte keepBasicPrinterInfo keine Bot Nachricht senden an Prusa Mini 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,685 - WS Thread - INFO - keepBasicPrinterInfo: Drucker Prusa Mini erzeugt neue MessageID: 0 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,686 - WS Thread - INFO - Drucker Thread initialisiert: Caribou 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,687 - WS Thread - INFO - Threads {'Repetier-Server-Order-Data', 'Repetier-Server-Restart-Threads', 'Repetier-Server-Receive', 'Repetier-Server-Send'} gestartet 
(Repetier-Server_Telegram_Bot) - 2020-11-23 23:20:40,687 - apscheduler.scheduler - INFO - Scheduler started 
(Repetier-Server-Order-Data) - 2020-11-23 23:20:42,540 - WS Thread - INFO - Drucker hinzugefuegt: Prusa Mini 
(Caribou   ) - 2020-11-23 23:20:43,051 - WS Thread - ERROR - Konnte msgPrinter keine Bot Nachricht senden an Caribou 
(Caribou   ) - 2020-11-23 23:20:43,053 - WS Thread - INFO - msgPrinter: Drucker Caribou erzeugt neue MessageID: 0 

```

Thanks ahead for helping us out.

**Comment by SebiWolze** [comment]
Okay found it!
My Chat ID is not my Username, its my Chat ID: 

  | 351826XXX
-- | --

Hard to find, but now I know it.
Maybe add it to your readme!
Bot working perfect so far.
THANKS!!!!!!!!!

**Comment by DanJunior78** [comment]
Perfekt, danke...
